### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vcabana**
Phase 1 propose changes.

### CODE REVIEW

**Comment by sic-f** [comment]
👍

**Comment by neilmarion** [comment]
👍

**Comment by neilmarion** [comment]
No one's stopping anyone from code-reviewing any PRs. It is just that people does not want to code review more than they want to. And that is the reason why we have to establish a rule so one PR is surely be code reviewed by anyone from the team and not by just a few select.

**Comment by deca7** [comment]
👍

**Comment by rickdtrick** [comment]
👍

**Comment by erbunao** [comment]
👍

**Comment by vcabana** [comment]
Thanks everyone!

**Pull request merged**
